# Generated by Django 4.2.6 on 2023-10-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
