# Generated by Django 4.2.6 on 2023-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0002_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment', to='webnews.comment'),
        ),
    ]
