# Generated by Django 4.2.6 on 2023-11-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0007_comment_news_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespComm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('post', models.IntegerField()),
                ('text', models.TextField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='resp',
            field=models.ManyToManyField(blank=True, related_name='comment', to='webnews.respcomm'),
        ),
    ]
